### PR TITLE
Add editProfile pane

### PR DESCRIPTION
**Pull request by timbl**
Moved from solid-panes.

### CODE REVIEW

**Comment by timbl** [comment]
Not sure why there is a  CI test using node 14.x 
when  the .github/workflows/ci.yml says
```
  node-version: [ 16.x, 18.x ]
```

**Review by chunt007 — COMMENTED** [review]
Are you meant to toggle between the profile-pane and edit profile pane seamlessly? solid panes repo lets me toggle when I load the panes individually. When I click on the edit button here, it attempts to load the pane but stays on the main profile.






My friends list is also gone. I have noticed that under languages, it now says Fr and En, instead of French and English.

This is on a fresh profile-pane install with the pull requests added.

**Comment by timbl** [comment]
"Are you meant to toggle between the profile-pane and edit profile pane seamlessly?" -- no that workflow with the edit button is just a placeholder.   This PR is just about refactoring the edit button code to be in the same repo.  Not supposed to be any functional changes.  

The "fr" for "french" suggests it is missing some labels.

**Comment by timbl** [comment]
image

**Pull request merged**
